# Name des HMM-Durchlaufs
name: TestRun1

# Welcher Datensatz soll verwendet werden?
# Möglichkeiten:
# - Gams
# - Deer
# - Ursina
# - Thomas
dataset_name: Deer

# Vorverarbeitung
# Möglichkeiten:
# - L2norm        # L2-Norm von X und Y
# - onlyX         # Nur X-Achse
# - XNotCensored  # X-Achse, nicht zensiert
# - sum       # sum aus X und Y
preprocessing: onlyX

# Anzahl der HMM-Zustände
# Beispiel: 2, 3, 4, ...
nbStates: 3

# Temperature
# Möglichkeiten:
# None
# Intern
# Extern
# Mix
# Rain
# only_Rain
temperature: Extern

# Transitions
#formula: "~1"
#formula: "~season"
#formula: "~temp"
#formula: "~ToD"
#formula: "~ToD + season + temp"
formula: "~1"


# Emission
#emission_mean: "~1"
#emission_mean: "~season"
#emission_mean: "~temp"
#emission_mean: "~ToD"
#emission_mean: "~ToD + season + temp"
emission_mean: "~1"

